-- MySQL Script generated by MySQL Workbench
-- Tue Sep 25 11:19:17 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema caixa
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `caixa` ;

-- -----------------------------------------------------
-- Schema caixa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `caixa` DEFAULT CHARACTER SET utf8 ;
USE `caixa` ;

-- -----------------------------------------------------
-- Table `caixa`.`Categorizacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caixa`.`Categorizacao` (
  `idCategorizacao` INT NOT NULL auto_increment ,
  `Descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCategorizacao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `caixa`.`Sub_categorizacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caixa`.`Sub_categorizacao` (
  `idSub_Categorizacao` INT NOT NULL auto_increment,
  `Descricao` VARCHAR(45) NOT NULL,
  `Categorizacao_idCategorizacao` INT NOT NULL,
  PRIMARY KEY (`idSub_Categorizacao`, `Categorizacao_idCategorizacao`),
  INDEX `fk_Sub_categorizacao_Categorizacao1_idx` (`Categorizacao_idCategorizacao` ASC),
  CONSTRAINT `fk_Sub_categorizacao_Categorizacao1`
    FOREIGN KEY (`Categorizacao_idCategorizacao`)
    REFERENCES `caixa`.`Categorizacao` (`idCategorizacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `caixa`.`Contas_Empresariais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caixa`.`Contas_Empresariais` (
  `idContas_Empresariais` INT NOT NULL AUTO_INCREMENT,
  `Descricao` VARCHAR(45) NOT NULL,
  `Saldoinicial` FLOAT NULL,
  PRIMARY KEY (`idContas_Empresariais`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `caixa`.`Operacao_caixa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caixa`.`Operacao_caixa` (
  `idOperacao_caixa` INT NOT NULL AUTO_INCREMENT,
  `Data` DATE NOT NULL,
  `Valor` FLOAT NOT NULL,
  `Sub_categorizacao_idSub_categorizacao` INT NOT NULL,
  `Contas_Empresariais_idContas_Empresariais` INT NOT NULL,
  PRIMARY KEY (`idOperacao_caixa`, `Sub_categorizacao_idSub_categorizacao`, `Contas_Empresariais_idContas_Empresariais`),
  INDEX `fk_Operacao_caixa_Sub_categorizacao1_idx` (`Sub_categorizacao_idSub_categorizacao` ASC),
  INDEX `fk_Operacao_caixa_Contas_Empresariais1_idx` (`Contas_Empresariais_idContas_Empresariais` ASC),
  CONSTRAINT `fk_Operacao_caixa_Sub_categorizacao1`
    FOREIGN KEY (`Sub_categorizacao_idSub_categorizacao`)
    REFERENCES `caixa`.`Sub_categorizacao` (`idSub_Categorizacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Operacao_caixa_Contas_Empresariais1`
    FOREIGN KEY (`Contas_Empresariais_idContas_Empresariais`)
    REFERENCES `caixa`.`Contas_Empresariais` (`idContas_Empresariais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `caixa`.`Sangria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caixa`.`Sangria` (
  `idSangria` INT NOT NULL AUTO_INCREMENT,
  `Valor` FLOAT NOT NULL,
  `Data` DATE NOT NULL,
  `Operacao_caixa_idOperacao_caixa` INT NOT NULL,
  PRIMARY KEY (`idSangria`, `Operacao_caixa_idOperacao_caixa`),
  INDEX `fk_Sangria_Operacao_caixa1_idx` (`Operacao_caixa_idOperacao_caixa` ASC),
  CONSTRAINT `fk_Sangria_Operacao_caixa1`
    FOREIGN KEY (`Operacao_caixa_idOperacao_caixa`)
    REFERENCES `caixa`.`Operacao_caixa` (`idOperacao_caixa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `caixa`.`Devolucao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caixa`.`Devolucao` (
  `idDevolucao` INT NOT NULL AUTO_INCREMENT,
  `Data` DATE NOT NULL,
  `ValorDevolvido` FLOAT NOT NULL,
  `NotadeDevolucao` INT NOT NULL,
  `Operacao_caixa_idOperacao_caixa` INT NOT NULL,
  PRIMARY KEY (`idDevolucao`, `Operacao_caixa_idOperacao_caixa`),
  INDEX `fk_Devolucao_Operacao_caixa1_idx` (`Operacao_caixa_idOperacao_caixa` ASC),
  CONSTRAINT `fk_Devolucao_Operacao_caixa1`
    FOREIGN KEY (`Operacao_caixa_idOperacao_caixa`)
    REFERENCES `caixa`.`Operacao_caixa` (`idOperacao_caixa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `caixa`.`Suprimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caixa`.`Suprimento` (
  `idSuprimento` INT NOT NULL auto_increment,
  `Valor` FLOAT NOT NULL,
  `Data` DATE NOT NULL,
  `Operacao_caixa_idOperacao_caixa` INT NOT NULL,
  PRIMARY KEY (`idSuprimento`, `Operacao_caixa_idOperacao_caixa`),
  INDEX `fk_Suprimento_Operacao_caixa_idx` (`Operacao_caixa_idOperacao_caixa` ASC),
  CONSTRAINT `fk_Suprimento_Operacao_caixa`
    FOREIGN KEY (`Operacao_caixa_idOperacao_caixa`)
    REFERENCES `caixa`.`Operacao_caixa` (`idOperacao_caixa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

create table if not exists `caixa`.`pedido`(
		id_pedido int  not null auto_increment,
        valorTotalPedido float,
        forma_pagamento varchar(45),
	PRIMARY KEY (`id_pedido`, `pedido_id_pedido`))
    ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
